version: '3.8'

services:
  sql_exporter:
    image: githubfree/sql_exporter
    container_name: sql_exporter
    ports:
      - "9187:9187"
    volumes:
      - ./sql_exporter.yml:/root/sql_exporter.yml

